# Generated by Django 4.1.7 on 2023-06-04 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userinfo',
        ),
    ]
