# Generated by Django 4.1.7 on 2023-06-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_userinformation_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
