# Generated by Django 4.1.7 on 2023-06-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
