# Generated by Django 4.1.7 on 2023-06-01 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
