# Generated by Django 4.1.7 on 2023-06-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_userinformation_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userinformation',
        ),
    ]
