# Generated by Django 4.1.7 on 2023-06-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_alter_userinformation_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='kodeposti',
            field=models.PositiveBigIntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='tel',
            field=models.PositiveBigIntegerField(blank=True, default=None),
        ),
    ]
