# Generated by Django 4.1.7 on 2023-06-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_alter_userinformation_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='tel',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
