# Generated by Django 4.1.7 on 2023-06-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0013_alter_userinformation_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='kodeposti',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
