# Generated by Django 4.1.7 on 2023-06-28 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0014_alter_userinformation_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspacename', models.CharField(max_length=255)),
                ('workspacetel', models.PositiveBigIntegerField()),
                ('kodeposti', models.PositiveBigIntegerField()),
                ('address', models.TextField(max_length=500)),
                ('describe', models.TextField(max_length=750)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.userinformation')),
            ],
        ),
    ]
