# Generated by Django 4.1.7 on 2023-06-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0016_alter_sellerrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerrequest',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
