# Generated by Django 4.1.7 on 2023-07-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0018_sellerrequest_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerrequest',
            name='date_created',
        ),
    ]
