# Generated by Django 4.1.7 on 2023-07-06 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0019_remove_sellerrequest_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerrequest',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
