# Generated by Django 4.1.7 on 2023-06-07 08:48

import Admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=255)),
                ('Image', models.ImageField(blank=True, null=True, upload_to=Admin.models.file_path)),
            ],
        ),
    ]
