# Generated by Django 4.1.7 on 2023-06-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='Title',
        ),
    ]
