# Generated by Django 4.1.7 on 2023-07-01 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_card_functiontodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='FunctionToDo',
        ),
    ]
