# Generated by Django 4.1.7 on 2023-06-19 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_category_description_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
