# Generated by Django 4.1.7 on 2023-06-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='count',
            new_name='countp',
        ),
        migrations.AlterField(
            model_name='order',
            name='orderstatus',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='sumprice',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
