# Generated by Django 4.1.7 on 2023-07-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_order_malyat'),
    ]

    operations = [
        migrations.CreateModel(
            name='malyatba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malyat', models.SmallIntegerField(default=0, null=True)),
            ],
        ),
    ]
