# Generated by Django 4.1.7 on 2023-06-07 08:30

import Seller.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Image',
            field=models.ImageField(null=True, upload_to=Seller.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='product',
            name='Price',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Qty',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Qtysell',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.category'),
        ),
    ]
