# Generated by Django 4.1.7 on 2023-06-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_product_description_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
