# Generated by Django 4.1.7 on 2023-06-28 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0004_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Qtysell',
        ),
    ]
