# Generated by Django 4.1.7 on 2023-07-06 16:25

import Seller.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_remove_category_description_remove_category_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Seller', '0006_product_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(default=None, upload_to=Seller.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.PositiveBigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='Qty',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='Size',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='Title',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='User',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Core.category'),
        ),
    ]
